import { Suspense } from "react"
import StyledComponentsRegistry from "../src/styles/StyledComponentsRegistry"
import { Space_Grotesk } from "next/font/google"
import { Provider } from "react-redux"
import { reduxStore } from "@/state"
import PostHog from "@/providers/PostHog"
import StoreProvider from "@/state/StoreProvider"
import "@/styles/globals.css"

export const metadata = {
  title: "Victory Nwani",
  description: "Generated by Next.js",
}

const font = Space_Grotesk({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "400", "600", "700"],
  style: ["normal"],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Suspense fallback={<div>Loading...</div>}>
            <PostHog>
              <StoreProvider>
                <div
                  style={{
                    height: "100vh",
                    overflow: "auto",
                    width: "100%",
                  }}
                  className={font.className}
                >
                  {children}
                </div>
              </StoreProvider>
            </PostHog>
          </Suspense>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
