[build]
command = "yarn build"
publish = ".next"
environment = { NODE_VERSION = "16", YARN_VERSION = "1.19.0" }

[dev]
port = 5050
autoLaunch = false

[functions]
included_files = ["functions/root.crt"]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[[plugins]]
package = "@netlify/plugin-nextjs"
