name: Portfolio Application C.I Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install npm
        run: |
          npm version
          npm ci
        env:
          CI: true

      - name: Install application dependencies
        run: npm install

      - name: Run Application Tests
        run: npm run test

      - name: Wait for Netlify preview deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: jakepartusch/wait-for-netlify-action@v1
        id: get-netlify-url
        with:
          site_name: "nwani"
          max_timeout: 180
