name: Portfolio Application C.I Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        name: Install PNPM

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install application dependencies
        run: pnpm install

      - name: Run Frontend Application Tests
        run: ls && cd ./apps/frontend && pnpm run test

      - name: Wait for Netlify preview deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: jakepartusch/wait-for-netlify-action@v1
        id: get-netlify-url
        with:
          site_name: "nwani"
          max_timeout: 180

      - name: Generate Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
          path_to_write_report: ./jest-coverage/codecov_report.txt
        
      - name: Run the semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
